name: PR Checks
on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - "*"
    
jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"
          cache: true
      
      - name: Lint gateway-service
        uses: golangci/golangci-lint-action@v8
        with: 
          version: v2.14
          working-directory: gateway-service
      
      - name: Test gateway-service
        working-directory: gateway-service
        run: go test ./...

      - name: Lint user-service
        uses: golangci/golangci-lint-action@v8
        with: 
          version: v2.14
          working-directory: user-service
      
      - name: Test user-service
        working-directory: user-service
        run: go test ./...
